import { useState } from 'react';
import { useApp } from '@/context/AppContext';
import { Button, EmptyState, ConfirmDialog } from '@/components/ui';
import { createCharacter } from '@/utils/factories';
import { generateCharacter } from '@/services/ai/engine';
import { Plus, Trash2, Edit3, Sparkles, Users, Copy } from 'lucide-react';
import type { Character } from '@/types';

export function Characters({ toastSuccess, toastError }: { toastSuccess: (m: string) => void; toastError: (m: string) => void }) {
  const { currentBook, characters, saveCharacter, deleteCharacter, settings } = useApp();
  const [editing, setEditing] = useState<Character | null>(null);
  const [confirmDelete, setConfirmDelete] = useState<Character | null>(null);
  const [generating, setGenerating] = useState(false);

  if (!currentBook) return null;

  const handleAdd = () => {
    const c = createCharacter(currentBook.id);
    saveCharacter(c);
    setEditing(c);
  };

  const handleGenerate = async () => {
    if (!settings?.aiSettings?.apiKey) { toastError('Set your AI API key in Settings first.'); return; }
    setGenerating(true);
    try {
      const partial = await generateCharacter(currentBook, settings.aiSettings);
      const c = { ...createCharacter(currentBook.id), ...partial, name: partial.name || 'New Character' };
      await saveCharacter(c);
      setEditing(c);
      toastSuccess('Character generated by AI');
    } catch (err) {
      toastError((err as Error).message);
    } finally {
      setGenerating(false);
    }
  };

  const handleDuplicate = (c: Character) => {
    const copy = { ...c, id: createCharacter(currentBook.id).id, name: `${c.name} (Copy)`, createdAt: Date.now(), updatedAt: Date.now() };
    saveCharacter(copy);
    toastSuccess('Character duplicated');
  };

  return (
    <div className="h-full overflow-y-auto bg-surface-50 dark:bg-surface-950">
      <div className="mx-auto max-w-4xl px-8 py-8">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-semibold text-surface-800 dark:text-surface-100">Characters</h1>
            <p className="text-sm text-surface-500 dark:text-surface-400">{characters.length} characters in your book</p>
          </div>
          <div className="flex gap-2">
            <Button variant="primary" icon={generating ? undefined : <Sparkles size={16} />} loading={generating} onClick={handleGenerate}>AI Generate</Button>
            <Button variant="secondary" icon={<Plus size={16} />} onClick={handleAdd}>Add Character</Button>
          </div>
        </div>

        {characters.length === 0 ? (
          <EmptyState icon={<Users size={48} />} title="No characters yet" description="Add characters to your book or let AI generate one for you." action={<Button variant="primary" icon={<Plus size={18} />} onClick={handleAdd}>Add Character</Button>} />
        ) : (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {characters.map((c) => (
              <div key={c.id} className="card-hover p-5">
                <div className="flex items-start gap-3 mb-3">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-white text-sm font-semibold" style={{ backgroundColor: c.color }}>
                    {c.name.charAt(0).toUpperCase()}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-medium text-surface-800 dark:text-surface-100 truncate">{c.name}</h3>
                    {c.role && <p className="text-xs text-accent-600 dark:text-accent-400">{c.role}</p>}
                  </div>
                </div>
                {c.personality && <p className="text-sm text-surface-500 dark:text-surface-400 line-clamp-2 mb-3">{c.personality}</p>}
                <div className="flex gap-2">
                  <Button variant="ghost" size="sm" icon={<Edit3 size={14} />} onClick={() => setEditing(c)}>Edit</Button>
                  <Button variant="ghost" size="sm" icon={<Copy size={14} />} onClick={() => handleDuplicate(c)}>Duplicate</Button>
                  <Button variant="ghost" size="sm" icon={<Trash2 size={14} />} onClick={() => setConfirmDelete(c)} className="text-error-500" />
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {editing && <CharacterEditor character={editing} onClose={() => setEditing(null)} onSave={(c) => { saveCharacter(c); setEditing(null); toastSuccess('Character saved'); }} />}

      <ConfirmDialog open={!!confirmDelete} onClose={() => setConfirmDelete(null)} onConfirm={() => { if (confirmDelete) { deleteCharacter(confirmDelete.id); toastSuccess('Character deleted'); } }} title="Delete Character" message={`Delete "${confirmDelete?.name}"?`} confirmLabel="Delete" danger />
    </div>
  );
}

function CharacterEditor({ character, onClose, onSave }: { character: Character; onClose: () => void; onSave: (c: Character) => void }) {
  const [c, setC] = useState(character);
  const update = (partial: Partial<Character>) => setC({ ...c, ...partial });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white dark:bg-surface-900 shadow-soft-lg">
        <div className="sticky top-0 flex items-center justify-between border-b border-surface-200 dark:border-surface-800 bg-white dark:bg-surface-900 px-6 py-4 z-10">
          <h2 className="text-lg font-semibold text-surface-800 dark:text-surface-100">Edit Character</h2>
          <div className="flex gap-2">
            <Button variant="ghost" onClick={onClose}>Cancel</Button>
            <Button variant="primary" onClick={() => onSave(c)}>Save</Button>
          </div>
        </div>
        <div className="p-6 space-y-4">
          <div className="grid grid-cols-3 gap-4">
            <div><label className="input-label">Name</label><input className="input" value={c.name} onChange={(e) => update({ name: e.target.value })} /></div>
            <div><label className="input-label">Age</label><input className="input" value={c.age} onChange={(e) => update({ age: e.target.value })} /></div>
            <div><label className="input-label">Gender</label><input className="input" value={c.gender} onChange={(e) => update({ gender: e.target.value })} /></div>
          </div>
          <div><label className="input-label">Role</label><input className="input" value={c.role} onChange={(e) => update({ role: e.target.value })} placeholder="Protagonist, Antagonist, Supporting..." /></div>
          <div><label className="input-label">Appearance</label><textarea className="textarea" value={c.appearance} onChange={(e) => update({ appearance: e.target.value })} /></div>
          <div><label className="input-label">Personality</label><textarea className="textarea" value={c.personality} onChange={(e) => update({ personality: e.target.value })} /></div>
          <div><label className="input-label">Background</label><textarea className="textarea" value={c.background} onChange={(e) => update({ background: e.target.value })} /></div>
          <div className="grid grid-cols-2 gap-4">
            <div><label className="input-label">Occupation</label><input className="input" value={c.occupation} onChange={(e) => update({ occupation: e.target.value })} /></div>
            <div><label className="input-label">Status</label><input className="input" value={c.status} onChange={(e) => update({ status: e.target.value })} /></div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div><label className="input-label">Goals</label><textarea className="textarea" value={c.goals} onChange={(e) => update({ goals: e.target.value })} /></div>
            <div><label className="input-label">Motivation</label><textarea className="textarea" value={c.motivation} onChange={(e) => update({ motivation: e.target.value })} /></div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div><label className="input-label">Fear</label><textarea className="textarea" value={c.fear} onChange={(e) => update({ fear: e.target.value })} /></div>
            <div><label className="input-label">Secrets</label><textarea className="textarea" value={c.secrets} onChange={(e) => update({ secrets: e.target.value })} /></div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div><label className="input-label">Strengths</label><textarea className="textarea" value={c.strengths} onChange={(e) => update({ strengths: e.target.value })} /></div>
            <div><label className="input-label">Weaknesses</label><textarea className="textarea" value={c.weaknesses} onChange={(e) => update({ weaknesses: e.target.value })} /></div>
          </div>
          <div><label className="input-label">Character Arc</label><textarea className="textarea" value={c.arc} onChange={(e) => update({ arc: e.target.value })} /></div>
          <div><label className="input-label">Important Facts</label><textarea className="textarea" value={c.importantFacts} onChange={(e) => update({ importantFacts: e.target.value })} /></div>
        </div>
      </div>
    </div>
  );
}
