import { useState } from 'react';
import { useApp } from '@/context/AppContext';
import { Button, ErrorBanner, TagInput } from '@/components/ui';
import { generateMetadata } from '@/services/ai/engine';
import { Sparkles, Save } from 'lucide-react';
import type { BookMetadata as Meta } from '@/types';

export function Metadata({ toastSuccess, toastError }: { toastSuccess: (m: string) => void; toastError: (m: string) => void }) {
  const { currentBook, saveBook, settings } = useApp();
  const [meta, setMeta] = useState<Meta>(currentBook?.metadata || createEmptyMeta());
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  if (!currentBook) return null;

  const handleSave = async () => {
    await saveBook({ ...currentBook, metadata: meta });
    toastSuccess('Metadata saved');
  };

  const handleGenerate = async () => {
    if (!settings?.aiSettings?.apiKey) { setError('Set your AI API key in Settings first.'); return; }
    setGenerating(true);
    setError('');
    try {
      const generated = await generateMetadata(currentBook, settings.aiSettings);
      setMeta({ ...meta, ...generated });
      toastSuccess('Metadata generated by AI');
    } catch (err) {
      setError((err as Error).message);
      toastError('Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const update = (partial: Partial<Meta>) => setMeta({ ...meta, ...partial });

  return (
    <div className="h-full overflow-y-auto bg-surface-50 dark:bg-surface-950">
      <div className="mx-auto max-w-3xl px-8 py-8">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-semibold text-surface-800 dark:text-surface-100">Book Metadata</h1>
            <p className="text-sm text-surface-500 dark:text-surface-400">Publishing description, keywords, and marketing copy.</p>
          </div>
          <div className="flex gap-2">
            <Button variant="primary" icon={generating ? undefined : <Sparkles size={16} />} loading={generating} onClick={handleGenerate}>Generate with AI</Button>
            <Button variant="secondary" icon={<Save size={16} />} onClick={handleSave}>Save</Button>
          </div>
        </div>

        {error && <div className="mb-4"><ErrorBanner message={error} onDismiss={() => setError('')} /></div>}

        <div className="space-y-5">
          <div className="card p-5">
            <label className="input-label">Tagline</label>
            <input className="input" value={meta.tagline} onChange={(e) => update({ tagline: e.target.value })} placeholder="A short memorable tagline" />
          </div>
          <div className="card p-5">
            <label className="input-label">Marketing Hook</label>
            <input className="input" value={meta.marketingHook} onChange={(e) => update({ marketingHook: e.target.value })} placeholder="One-line marketing hook" />
          </div>
          <div className="card p-5">
            <label className="input-label">Short Description</label>
            <textarea className="textarea" value={meta.shortDescription} onChange={(e) => update({ shortDescription: e.target.value })} placeholder="1-2 sentence hook for retailers" />
          </div>
          <div className="card p-5">
            <label className="input-label">Long Description</label>
            <textarea className="textarea min-h-[120px]" value={meta.longDescription} onChange={(e) => update({ longDescription: e.target.value })} placeholder="3-4 paragraph compelling book description" />
          </div>
          <div className="card p-5">
            <label className="input-label">Back Cover Text</label>
            <textarea className="textarea" value={meta.backCoverText} onChange={(e) => update({ backCoverText: e.target.value })} />
          </div>
          <div className="card p-5">
            <label className="input-label">Author Bio</label>
            <textarea className="textarea" value={meta.authorBio} onChange={(e) => update({ authorBio: e.target.value })} />
          </div>
          <div className="card p-5">
            <label className="input-label">Keywords</label>
            <TagInput tags={meta.keywords} onChange={(keywords) => update({ keywords })} placeholder="Add a keyword..." />
          </div>
          <div className="card p-5">
            <label className="input-label">Categories</label>
            <TagInput tags={meta.categories} onChange={(categories) => update({ categories })} placeholder="Add a category..." />
          </div>
          <Button variant="primary" icon={<Save size={16} />} onClick={handleSave}>Save Metadata</Button>
        </div>
      </div>
    </div>
  );
}

function createEmptyMeta(): Meta {
  return { shortDescription: '', longDescription: '', authorBio: '', keywords: [], categories: [], marketingHook: '', tagline: '', backCoverText: '' };
}
