import { useState } from 'react';
import { useApp } from '@/context/AppContext';
import { Button, ErrorBanner } from '@/components/ui';
import { TagInput } from '@/components/ui';
import { generateBookBible } from '@/services/ai/engine';
import { Sparkles, Save } from 'lucide-react';
import type { BookBible } from '@/types';

export function StoryBible({ toastSuccess, toastError }: { toastSuccess: (m: string) => void; toastError: (m: string) => void }) {
  const { currentBook, saveBook, settings } = useApp();
  const [bible, setBible] = useState<BookBible>(currentBook?.bible || createEmptyBible());
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  if (!currentBook) return null;

  const handleSave = async () => {
    await saveBook({ ...currentBook, bible });
    toastSuccess('Story Bible saved');
  };

  const handleGenerate = async () => {
    if (!settings?.aiSettings?.apiKey) { setError('Set your AI API key in Settings first.'); return; }
    setGenerating(true);
    setError('');
    try {
      const generated = await generateBookBible({ book: currentBook, aiSettings: settings.aiSettings });
      setBible({ ...bible, ...generated, genre: currentBook.genre, subgenre: currentBook.subgenre });
      toastSuccess('Story Bible generated by AI');
    } catch (err) {
      setError((err as Error).message);
      toastError('Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const update = (partial: Partial<BookBible>) => setBible({ ...bible, ...partial });

  return (
    <div className="h-full overflow-y-auto bg-surface-50 dark:bg-surface-950">
      <div className="mx-auto max-w-3xl px-8 py-8">
        <div className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-semibold text-surface-800 dark:text-surface-100">Story Bible</h1>
            <p className="text-sm text-surface-500 dark:text-surface-400">Persistent context used by the AI when generating chapters.</p>
          </div>
          <div className="flex gap-2">
            <Button variant="primary" icon={generating ? undefined : <Sparkles size={16} />} loading={generating} onClick={handleGenerate}>Generate with AI</Button>
            <Button variant="secondary" icon={<Save size={16} />} onClick={handleSave}>Save</Button>
          </div>
        </div>

        {error && <div className="mb-4"><ErrorBanner message={error} onDismiss={() => setError('')} /></div>}

        <div className="space-y-5">
          <Section title="Story Premise">
            <textarea className="textarea min-h-[80px]" value={bible.premise} onChange={(e) => update({ premise: e.target.value })} placeholder="The core premise of your story..." />
          </Section>

          <Section title="Themes">
            <TagInput tags={bible.themes} onChange={(themes) => update({ themes })} placeholder="Add a theme..." />
          </Section>

          <div className="grid grid-cols-2 gap-4">
            <Section title="Genre">
              <input className="input" value={bible.genre} onChange={(e) => update({ genre: e.target.value })} />
            </Section>
            <Section title="Subgenre">
              <input className="input" value={bible.subgenre} onChange={(e) => update({ subgenre: e.target.value })} />
            </Section>
          </div>

          <Section title="Tone">
            <input className="input" value={bible.tone} onChange={(e) => update({ tone: e.target.value })} placeholder="e.g. Dark and atmospheric" />
          </Section>

          <Section title="Point of View">
            <input className="input" value={bible.pointOfView} onChange={(e) => update({ pointOfView: e.target.value })} placeholder="e.g. Third Person Limited" />
          </Section>

          <Section title="Timeline">
            <textarea className="textarea" value={bible.timeline} onChange={(e) => update({ timeline: e.target.value })} placeholder="Timeline of events in your story..." />
          </Section>

          <Section title="World Rules">
            <TagInput tags={bible.worldRules} onChange={(worldRules) => update({ worldRules })} placeholder="Add a world rule..." />
          </Section>

          <Section title="Important Facts">
            <TagInput tags={bible.importantFacts} onChange={(importantFacts) => update({ importantFacts })} placeholder="Add an important fact..." />
          </Section>

          <Section title="Plot Threads">
            <div className="space-y-2">
              {bible.plotThreads.map((pt, i) => (
                <div key={pt.id} className="flex items-start gap-2 rounded-lg bg-surface-100 dark:bg-surface-800 p-3">
                  <div className="flex-1">
                    <input className="input mb-2" value={pt.name} onChange={(e) => { const threads = [...bible.plotThreads]; threads[i] = { ...pt, name: e.target.value }; update({ plotThreads: threads }); }} placeholder="Thread name" />
                    <textarea className="textarea text-sm" value={pt.description} onChange={(e) => { const threads = [...bible.plotThreads]; threads[i] = { ...pt, description: e.target.value }; update({ plotThreads: threads }); }} placeholder="Description" />
                  </div>
                  <button onClick={() => update({ plotThreads: bible.plotThreads.filter((_, idx) => idx !== i) })} className="text-surface-400 hover:text-error-500">Remove</button>
                </div>
              ))}
              <Button variant="ghost" size="sm" onClick={() => update({ plotThreads: [...bible.plotThreads, { id: `pt-${Date.now()}`, name: '', description: '', status: 'open' }] })}>+ Add Plot Thread</Button>
            </div>
          </Section>

          <Section title="Open Questions">
            <TagInput tags={bible.openQuestions} onChange={(openQuestions) => update({ openQuestions })} placeholder="Add an open question..." />
          </Section>

          <Section title="Ending">
            <textarea className="textarea min-h-[80px]" value={bible.ending} onChange={(e) => update({ ending: e.target.value })} placeholder="How does the story end?" />
          </Section>

          <div className="pt-4">
            <Button variant="primary" icon={<Save size={16} />} onClick={handleSave}>Save Story Bible</Button>
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="card p-5">
      <h3 className="mb-3 font-medium text-surface-800 dark:text-surface-100">{title}</h3>
      {children}
    </div>
  );
}

function createEmptyBible(): BookBible {
  return { premise: '', themes: [], genre: '', subgenre: '', tone: '', writingStyleSummary: '', pointOfView: '', timeline: '', worldRules: [], importantFacts: [], plotThreads: [], openQuestions: [], ending: '' };
}
